apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-ui-deployment
spec:
  selector:
    matchLabels:
      app: storage-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: storage-ui
    spec:
      containers:
      - name: storage-ui
        image: 192.168.1.23:5000/homelab/storage-ui:latest
        env:
        - name: REACT_APP_DOMAIN
          value: "http://192.168.1.65"
        ports:
        - containerPort: 3000
          protocol: TCP
      nodeSelector:
        default: "true"

